supabase:
  url: "https://pmoamjggvhlpwfzhkrkp.supabase.co"
  key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtb2FtamdndmhscHdmemhrcmtwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTc1OTgyNCwiZXhwIjoyMDcxMzM1ODI0fQ.vvVe1lOyji5uyUyTT_UdVVnWsRAGDhZVDzG46aNiic0"
